# command to run: docker-compose up

version: "3"

services:
  elasticsearch:
    container_name: elk-boilerplate-elasticsearch
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    image: elasticsearch:7.2.0
    networks: 
      - logging-network
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  logstash:
    container_name: elk-boilerplate-logstash
    depends_on: 
      - elasticsearch
    image: logstash:7.2.0
    networks: 
      - logging-network
    ports:
      - 12201:12201/udp
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  kibana:
    container_name: elk-boilerplate-kibana
    depends_on: 
      - logstash
    image: kibana:7.2.0
    networks: 
      - logging-network
    ports:
      - 5601:5601

  nginx:
    container_name: elk-boilerplate-nginx
    depends_on: 
      - logstash
    image: nginx:1.16.0
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    ports:
      - 8080:80

networks: 
  logging-network:
    driver: bridge