# command to run: docker-compose up

version: "3"

services:
  elasticsearch:
    container_name: elk-boilerplate-elasticsearch
    image: elasticsearch:7.2.0
    ports:
      - 9200:9200
    restart: always

  logstash:
    container_name: elk-boilerplate-logstash
    image: logstash:7.2.0
    ports:
      - 12201:12201
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro